export const REQUIRED_INSTRUCTIONS = [
  "initializeProgramConfig",
  "setProgramConfigAuthority",
  "setProgramConfigSmartAccountCreationFee",
  "setProgramConfigTreasury",
  "createSmartAccount",
  "addSignerAsAuthority",
  "removeSignerAsAuthority",
  "setTimeLockAsAuthority",
  "changeThresholdAsAuthority",
  "setNewSettingsAuthorityAsAuthority",
  "setArchivalAuthorityAsAuthority",
  "addSpendingLimitAsAuthority",
  "removeSpendingLimitAsAuthority",
  "createSettingsTransaction",
  "executeSettingsTransaction",
  "createTransaction",
  "createTransactionBuffer",
  "closeTransactionBuffer",
  "extendTransactionBuffer",
  "createTransactionFromBuffer",
  "executeTransaction",
  "createBatch",
  "addTransactionToBatch",
  "executeBatchTransaction",
  "createProposal",
  "activateProposal",
  "approveProposal",
  "rejectProposal",
  "cancelProposal",
  "useSpendingLimit",
  "closeSettingsTransaction",
  "closeTransaction",
  "closeEmptyPolicyTransaction",
  "closeBatchTransaction",
  "closeBatch",
  "executeTransactionSync",
  "executeTransactionSyncV2",
  "executeSettingsTransactionSync",
  "logEvent",
] as const;

export const REQUIRED_ACCOUNTS = [
  "Batch",
  "BatchTransaction",
  "LegacyTransaction",
  "Policy",
  "ProgramConfig",
  "Proposal",
  "Settings",
  "SettingsTransaction",
  "SpendingLimit",
  "Transaction",
  "TransactionBuffer",
] as const;

export const IGNORED_IDL_TYPES = [
  "Permission",
  "TransactionMessage",
  "CompiledInstruction",
  "MessageAddressTableLookup",
  "CreateSmartAccountEvent",
  "SynchronousTransactionEvent",
  "SynchronousSettingsTransactionEvent",
  "AddSpendingLimitEvent",
  "RemoveSpendingLimitEvent",
  "UseSpendingLimitEvent",
  "TransactionEvent",
  "ProposalEvent",
  "SettingsChangePolicyEvent",
  "SmartAccountEvent",
  "ConsensusAccount",
  "SynchronousTransactionEventV2",
  "AuthoritySettingsEvent",
  "AuthorityChangeEvent",
  "TransactionContent",
] as const;
