import "./globals.css";
import "@telegram-apps/telegram-ui/dist/styles.css";

import { AppRoot } from "@telegram-apps/telegram-ui";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { TelegramProvider } from "@/components/telegram/TelegramProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
      <AppRoot suppressHydrationWarning>
        <TelegramProvider>
          {children}
        </TelegramProvider>
      </AppRoot>
    </body>
  </html>
  );
}
