import "@telegram-apps/telegram-ui/dist/styles.css";
import "./globals.css";

import { AppRoot } from "@telegram-apps/telegram-ui";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";

import { AnalyticsBootstrapClient } from "@/components/analytics/AnalyticsBootstrapClient";
import { TelegramProvider } from "@/components/telegram/TelegramProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <Script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="f6491a00-a838-4c1d-aa01-4f61ff790967"
          strategy="afterInteractive"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
        <AppRoot suppressHydrationWarning>
          <AnalyticsBootstrapClient />
          <TelegramProvider>
            {children}
          </TelegramProvider>
        </AppRoot>
      </body>
    </html>
  );
}
